-- schema.sql — Đã chuyển thành migration, file này chỉ còn là lối chỉ đường.
--
-- Nội dung thật nằm ở:
--   supabase/migrations/20260903000000_leaderboard.sql
--
-- Vì sao chuyển: migration có đánh số phiên bản, nên lần sau sửa cấu trúc bảng
-- thì thêm một file mới bên cạnh, chứ không sửa đè lên cái cũ. Muốn biết cơ sở
-- dữ liệu đã đi qua những bước nào, đọc thư mục đó theo thứ tự là ra.
--
-- Đẩy lên Supabase:
--   supabase db push
--
-- Dán tay cũng vẫn được: mở file migration, copy hết, dán vào SQL Editor.
